default:
  image: node:24.19.0-bookworm-slim@sha256:a9f5f7c91a432850b2a8a7797adf5eadb6c733ceed61167806cee7ea7fbc29df
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/

stages:
  - verify

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'

verify:
  stage: verify
  timeout: 20m
  interruptible: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - npm ci
    - npm run build
    - npm run lint
    - npm run test:ci
    - npm run audit:dev
    - npm run audit:prod
    - npm run verify:package
